name: Continous Integration

on: 
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout src code
        uses: actions/checkout@v4

      - name: Setup Node.js env
        uses: actions/setup-node@v4
        with:
            node-version: '20'
            cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Run unit tests
        run: npm test